### ISSUE TITLE
Whisper node

### ISSUE THREAD

**Issue by sadamyne** [domoszlai/arduino-proximity-sensor#2]
Hi,

I was trying to run your code in a Whisper Node but i got the folowing errors:
`

sketch\frequency_counter_attiny.cpp: In function 'long unsigned int count_frequency(uint8_t)':

sketch\frequency_counter_attiny.cpp:31:3: error: 'GIMSK' was not declared in this scope

   GIMSK = 0b00100000;

   ^

sketch\frequency_counter_attiny.cpp:32:3: error: 'PCMSK' was not declared in this scope

   PCMSK |= _BV(pin);

   ^

sketch\frequency_counter_attiny.cpp:35:3: error: 'TCCR1' was not declared in this scope

   TCCR1 = _BV(CTC1);            // CTC mode

   ^

In file included from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28,

                 from sketch\frequency_counter_attiny.cpp:1:

sketch\frequency_counter_attiny.cpp:35:15: error: 'CTC1' was not declared in this scope

   TCCR1 = _BV(CTC1);            // CTC mode

               ^

sketch\frequency_counter_attiny.cpp:43:3: error: 'OCR1C' was not declared in this scope

   OCR1C = 250;

   ^

sketch\frequency_counter_attiny.cpp:44:3: error: 'TIMSK' was not declared in this scope

   TIMSK |= _BV(OCIE1A);         // enable Timer1 interrupt

   ^

sketch\frequency_counter_attiny.cpp: In function 'void TIM1_COMPA_vect()':

sketch\frequency_counter_attiny.cpp:65:5: error: 'TIMSK' was not declared in this scope

     TIMSK &= ~_BV(OCIE1A);      // disable Timer1 Interrupt

     ^

exit status 1
Error compiling for board Talk2 Whisper Node.
`
Im i doing something wrong or is it just the board that doesnt support it?

Thanks in advance

**Comment by domoszlai** [comment]
Whisper node doesn't have ATMega328p? Do not use the attiny version then

**Comment by sadamyne** [comment]
Hi,
My fault i thought you had to place all the files in the sketch folder.
Can the "antena" pin be changed?
Thanks in advance

**Comment by domoszlai** [comment]
It uses the TC version of the frequency counter, so I'm afraid not. You can experiment with the PCI version., then you should have more options.

https://github.com/domoszlai/arduino-frequency-counter
